version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: blog_api_prod
    ports:
      - "3002:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      backend:

  mongodb:
    image: mongo:latest
    container_name: blog_mongodb
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - ./mongo_blog_app_prod:/data/db
    networks:
      backend:

volumes:
  mongo:

networks:
  backend: